<?php
namespace Codecademy;

// Write your code below:

//NOTES
//Generating Random Numbers:
//Purpose: randomize data for testing 

//rand()
//returns a random integer between 0 and the largest number the environment will allow 
//getrandmax() returns the largest possible random integer 
$max = getrandmax();
echo $max;
echo "\n";
//this will be a number between 0 and max 
echo rand();
echo "\n";
echo rand(1, 2); // Prints either 1 or 2
echo "\n";
echo rand(5, 10); // Prints a number between 5 and 10 (inclusive!)
//inclusive: arguments we pass in can be generated by a function
 echo "\n";
echo rand(1, 100); // Prints a number between 1 and 100 (inclusive!)
 echo "\n";
 echo rand(1, 52);
